Added inputs
talegraph/styles pull request #1
Opened 2017-03-28 14:36 UTC by MikaelSkoglund

ALBEEE kolla mina inputs, dom blev jättefina tycker jag. Haaej!

2017-03-29 14:28 UTC, eskilfogelstrom commented on src/index.html
> +
This is a nice example of when something consists of multiple components. First we have a list of things (could be anything). Within that list we have some draggable items.
```html
<div class="list">
  <div class="list__item draggable">...</div>
</div>
```
Each item also has two modifiers. When it's being dragged and a placeholder for the item being dragged. To preview how it looks, make a list like this:
```html
<div class="list">
  <div class="list__item draggable">...</div><!-- Normal -->
  <div class="list__item draggable--dragged">...</div><!-- When it's being dragged -->
  <div class="list__item draggable--placeholder">...</div><!-- Placeholder for the element being dragged -->
</div>
```

2017-03-29 14:28 UTC, eskilfogelstrom commented on src/index.html
> +      <div class="dimensions__variables">
Same thing here with multiple components. The boxes where you drop stuff can be considered cards and should then use the `.card` class. The area where you actually drop things is a separate class and is essentially the same as the `.draggable--placeholder` above.

2017-03-29 15:57 UTC, eskilfogelstrom requested changes

2017-03-29 15:57 UTC, eskilfogelstrom commented on src/styles/atoms/_buttons.scss
> +.button__input{
This can be removed no? :trollface:

2017-03-29 15:57 UTC, eskilfogelstrom commented on src/styles/atoms/_draggable.scss
> +  font-size: $font-size-l;
Not sure if the font size should be so large. What do you think?

2017-03-29 15:57 UTC, eskilfogelstrom commented on src/styles/atoms/_draggable.scss
> +  cursor: move;
This gets overwritten below so you can just remove it

2017-03-29 15:57 UTC, eskilfogelstrom commented on src/styles/atoms/_draggable.scss
> +  cursor: -webkit-grab;
Can only be `grab`

2017-03-29 15:57 UTC, eskilfogelstrom commented on src/styles/atoms/_draggable.scss
> +    cursor: -webkit-grabbing;
☝️  `grabbing`

2017-03-29 15:57 UTC, eskilfogelstrom commented on src/styles/atoms/_inputs.scss
> +.title__input{
Remove this file

2017-03-29 15:57 UTC, eskilfogelstrom commented on src/styles/atoms/_list__item.scss
> +.list__item{
Remove this file

2017-03-29 15:57 UTC, eskilfogelstrom commented on src/styles/atoms/_typography.scss
> +.list__title{
Remove since it's not used

2017-03-29 16:08 UTC, MikaelSkoglund commented on src/styles/atoms/_draggable.scss
> +  cursor: move;
Shady shit happened when I tried to remove this, I'll just wait with it

2017-03-29 16:09 UTC, MikaelWeidenhielm commented on src/styles/atoms/_draggable.scss
> +  cursor: -webkit-grab;
Doesn't actually respond to `grab` for some reason

2017-03-30 08:07 UTC, eskilfogelstrom approved these changes

2017-03-30 08:07 UTC, eskilfogelstrom commented
Nice job micke2000

2017-03-30 08:10 UTC, merged